import type { Project } from "./types";
export const projects: Project[] = [
 {slug:"production-data-infrastructure",index:"01",category:{en:"Production infrastructure",ar:"بنية إنتاجية"},title:{en:"Data infrastructure across nine servers",ar:"بنية بيانات عبر تسعة خوادم"},summary:{en:"Day-to-day ownership of production databases and data services across a multi-server environment.",ar:"مسؤولية يومية عن قواعد البيانات وخدمات البيانات الإنتاجية ضمن بيئة متعددة الخوادم."},role:{en:"Database Administrator / Database Engineer",ar:"مدير ومهندس قواعد بيانات"},technologies:["PostgreSQL","Linux","Prometheus","Grafana"],coverImage:"/projects/enterprise-operations.webp",coverAlt:{en:"Abstract illustration of interconnected enterprise operations modules.",ar:"رسم تجريدي لوحدات عمليات مؤسسية مترابطة."},status:{en:"Verified scope from CV; deeper case study pending evidence.",ar:"نطاق موثّق من السيرة؛ تفاصيل دراسة الحالة بانتظار الأدلة."},sections:[{title:{en:"Verified scope",ar:"النطاق الموثّق"},body:{en:"Production operations, health checks, troubleshooting, capacity planning, access control, and proactive monitoring.",ar:"عمليات الإنتاج، وفحوصات الصحة، واستكشاف المشكلات، وتخطيط السعة، وضبط الوصول، والمراقبة الاستباقية."}}]},
 {slug:"postgresql-high-availability",index:"02",category:{en:"High availability",ar:"التوافر العالي"},title:{en:"PostgreSQL HA & replication",ar:"التوافر العالي والتكرار لـ PostgreSQL"},summary:{en:"Implementation and operation of resilient PostgreSQL environments with routing and failover components.",ar:"تنفيذ وتشغيل بيئات PostgreSQL موثوقة مع مكونات التوجيه والتحول عند الفشل."},role:{en:"Database Administrator / Database Engineer",ar:"مدير ومهندس قواعد بيانات"},technologies:["Pigsty","Patroni","etcd","HAProxy","VIP"],coverImage:"/projects/data-integration.webp",coverAlt:{en:"Abstract illustration of enterprise systems exchanging data through a central integration hub.",ar:"رسم تجريدي لأنظمة مؤسسية تتبادل البيانات عبر مركز تكامل موحد."},status:{en:"Architecture detail withheld until supporting evidence is provided.",ar:"تفاصيل المعمارية مؤجلة حتى توفير أدلة داعمة."},sections:[{title:{en:"Verified implementation",ar:"التنفيذ الموثّق"},body:{en:"High-availability and replication environments operated in production using Pigsty, Patroni, etcd, and HAProxy/VIP.",ar:"بيئات توافر عالٍ وتكرار تعمل في الإنتاج باستخدام Pigsty وPatroni وetcd وHAProxy/VIP."}}]},
 {slug:"smart-library",index:"03",category:{en:"University internship",ar:"تدريب جامعي"},title:{en:"Smart Library",ar:"المكتبة الذكية"},summary:{en:"A Flutter project supporting a book-borrowing workflow during a six-month internship at YemenSoft.",ar:"مشروع Flutter لإدارة سير عمل استعارة الكتب خلال تدريب لمدة ستة أشهر في يمن سوفت."},role:{en:"University Intern",ar:"متدرب جامعي"},technologies:["Flutter"],coverImage:"/projects/government-services.webp",coverAlt:{en:"Abstract illustration of digital services connected through a unified portal.",ar:"رسم تجريدي لخدمات رقمية متصلة عبر بوابة موحدة."},status:{en:"Project outcomes and screenshots pending evidence.",ar:"نتائج المشروع ولقطات الشاشة بانتظار الأدلة."},sections:[{title:{en:"Context",ar:"السياق"},body:{en:"University internship at YemenSoft in 2022, lasting six months.",ar:"تدريب جامعي في يمن سوفت عام 2022 لمدة ستة أشهر."}}]}
];

// Approved visual mappings retained for future verified case-study entries.
export const projectCoverCatalog = {
  "Enterprise Operations Platform":"/projects/enterprise-operations.webp",
  "Digital Identity Integration Platform":"/projects/digital-identity.webp",
  "Government Service Portal":"/projects/government-services.webp",
  "Customer Support Management System":"/projects/customer-support.webp",
  "CI/CD & Deployment Platform":"/projects/cicd-deployment.webp",
  "Enterprise Data Integration Hub":"/projects/data-integration.webp"
} as const;
