import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale, ui } from "@/lib/i18n";
import { profile } from "@/content/profile";
import { projects } from "@/content/projects";
import { capabilities, skillGroups } from "@/content/skills";
import { experience } from "@/content/experience";
import { education } from "@/content/education";
import { LineReveal, Reveal, Stagger, StaggerItem } from "@/components/motion/reveal";
import { SectionHeading } from "@/components/section-heading";
import { HeroArtwork } from "@/components/hero-artwork";
import { ProjectImage } from "@/components/project-image";
import { ProfilePortrait } from "@/components/profile-portrait";
import { GlobalScrollTechVessel } from "@/components/global-scroll-tech-vessel";
import type { Metadata } from "next";

export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{
 const {locale}=await params;if(!isLocale(locale))return {};
 const title=locale==="en"?"Mahmoud Abdulghani Almaqrami — Full-Stack Software Engineer":"محمود عبدالغني المقرمي — مهندس برمجيات متكامل";
 const description=locale==="en"?"Full-stack software engineering across systems integration, DevOps, database engineering, and production delivery.":"هندسة برمجيات متكاملة تشمل تكامل الأنظمة وDevOps وهندسة قواعد البيانات والنشر في بيئات الإنتاج.";
 return {title:{absolute:title},description,alternates:{canonical:`/${locale}/`,languages:{en:"/en/",ar:"/ar/"}},openGraph:{title,description,locale:locale==="en"?"en_US":"ar_YE"}};
}

export default async function Home({params}:{params:Promise<{locale:string}>}){
 const {locale:l}=await params;if(!isLocale(l))notFound();const locale=l,t=ui[locale];
 const structuredData={"@context":"https://schema.org","@type":"Person",name:profile.displayName[locale],jobTitle:profile.title[locale],description:t.support,knowsAbout:["Full-Stack Software Engineering","Systems Integration","DevOps","Database Engineering","PostgreSQL"],email:`mailto:${profile.email}`,telephone:profile.phone,address:{"@type":"PostalAddress",addressLocality:profile.location[locale]},knowsLanguage:profile.languages.map(x=>x.name.en)};
 return <><GlobalScrollTechVessel/><main id="top"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/>
  <section className="hero container"><div className="hero-copy"><Reveal><p className="identity">{profile.displayName[locale]}</p></Reveal><Reveal delay={.06}><p className="professional-title">{profile.title[locale]}</p></Reveal><Reveal delay={.1}><div className="hero-kicker"><span className="status-dot"/>{t.eyebrow}</div></Reveal><Reveal delay={.14}><h1>{t.statement}</h1></Reveal><Reveal delay={.2}><p className="hero-support">{t.support}</p></Reveal><Reveal delay={.26}><div className="hero-actions"><a href="#work" className="button primary">{t.allWork}<span>↘</span></a><a href={`mailto:${profile.email}`} className="button secondary">{t.discuss}<span>↗</span></a></div></Reveal></div><Reveal className="hero-art"><HeroArtwork alt={locale==="en"?"Abstract illustration of a complete software system connecting interfaces, services, infrastructure, and data.":"رسم تجريدي لنظام برمجي متكامل يربط الواجهات والخدمات والبنية التحتية والبيانات."}/></Reveal><div className="hero-meta"><span>{profile.location[locale]}</span><span>© 2026</span><span>Scroll ↓</span></div></section>
  <section id="work" className="section container"><SectionHeading index="01" eyebrow={t.work} title={locale==="en"?"Systems shaped by real operational responsibility.":"أنظمة صاغتها مسؤولية تشغيلية حقيقية."}/><div className="projects">{projects.map((p,i)=><article className={`project ${i%2?"reverse":""}`} key={p.slug}><div className="project-visual"><ProjectImage src={p.coverImage} alt={p.coverAlt[locale]} locale={locale} index={i}/></div><Reveal className="project-copy"><span className="project-number">/{p.index}</span><p className="eyebrow">{p.category[locale]}</p><h3>{p.title[locale]}</h3><p>{p.summary[locale]}</p><dl><div><dt>{locale==="en"?"Role":"الدور"}</dt><dd>{p.role[locale]}</dd></div>{p.technologies.length>0&&<div><dt>{locale==="en"?"Stack":"التقنيات"}</dt><dd>{p.technologies.join(" · ")}</dd></div>}</dl><div className="project-links"><Link href={`/${locale}/work/${p.slug}`} className="text-link">{t.view}<span>↗</span></Link>{p.liveUrl&&<a href={p.liveUrl} target="_blank" rel="noopener noreferrer" className="text-link live-project-link">{locale==="en"?"Visit Live Website":"زيارة الموقع"}<span>↗</span></a>}</div></Reveal></article>)}</div></section>
  <section id="expertise" className="section expertise"><div className="container"><SectionHeading index="02" eyebrow={t.expertise} title={locale==="en"?"Complete systems, thoughtfully connected.":"أنظمة متكاملة، مترابطة بعناية."}/><Stagger className="capability-list">{capabilities.map(c=><StaggerItem className="capability" key={c.n}><span>{c.n}</span><h3>{c.title[locale]}</h3><p>{c.text[locale]}</p><b>↗</b><LineReveal/></StaggerItem>)}</Stagger></div></section>
  <section className="section process-section"><div className="container"><SectionHeading index="03" eyebrow={t.process} title={locale==="en"?"A deliberate path from context to improvement.":"مسار مدروس من فهم السياق إلى التحسين."}/><Stagger className="process-flow"><LineReveal/>{t.processSteps.map((step,i)=><StaggerItem className="process-step" key={step}><span>{String(i+1).padStart(2,"0")}</span><strong>{step}</strong></StaggerItem>)}</Stagger></div></section>
  <section id="experience" className="section container"><SectionHeading index="04" eyebrow={t.experience} title={locale==="en"?"Operating where uptime matters.":"عملٌ حيث يكون وقت التشغيل مهمًا."}/>{experience.map(x=><div className="experience" key={x.dates.en}><Reveal className="experience-meta"><span>{x.dates[locale]}</span><h3>{x.organization[locale]}</h3><p>{x.location[locale]}</p></Reveal><div><Reveal><p className="role">{x.jobTitle[locale]}</p></Reveal><Stagger className="responsibilities">{x.responsibilities[locale].map(item=><StaggerItem key={item}><p>{item}</p></StaggerItem>)}</Stagger><Reveal><div className="platforms">{x.platforms[locale].map(p=><span key={p}>{p}</span>)}</div></Reveal></div></div>)}</section>
  <section className="section capabilities-section"><div className="container"><SectionHeading index="05" eyebrow={locale==="en"?"Technical capabilities":"القدرات التقنية"} title={locale==="en"?"Capabilities across the full system lifecycle.":"قدرات تمتد عبر دورة حياة النظام كاملة."}/><Stagger className="skills-grid">{skillGroups.map(g=><StaggerItem className="skill-group" key={g.title.en}><h3>{g.title[locale]}</h3><p>{g.items.join(" · ")}</p></StaggerItem>)}</Stagger></div></section>
  <section id="about" className="section container"><SectionHeading index="06" eyebrow={t.about} title={locale==="en"?"An engineer who thinks end-to-end.":"مهندس يفكر في النظام من البداية إلى النهاية."}/><div className="about-grid"><ProfilePortrait alt={locale==="en"?"Portrait of Mahmoud Abdulghani Almaqrami":"صورة محمود عبدالغني المقرمي"}/><Stagger className="about-content"><StaggerItem><p className="about-lead">{profile.summary[locale]}</p></StaggerItem><StaggerItem className="education"><h3>{t.education}</h3>{education.map(e=><div className="education-item" key={e.title.en}><div><strong>{e.title[locale]}</strong><span>{e.place[locale]}</span></div><small>{e.meta[locale]}</small></div>)}</StaggerItem><StaggerItem><div className="languages"><h3>{t.languages}</h3>{profile.languages.map(x=><span key={x.name.en}>{x.name[locale]} — {x.level[locale]}</span>)}</div></StaggerItem></Stagger></div></section>
  <section className="section writing container"><SectionHeading index="07" eyebrow={t.writing} title={locale==="en"?"Writing grounded in practice.":"كتابة تنطلق من الممارسة."}/><Reveal><div className="writing-empty"><span>{locale==="en"?"FIELD NOTES":"ملاحظات ميدانية"}</span><p>{t.writingText}</p></div></Reveal></section>
  <section id="contact" className="contact-section"><div className="container"><Stagger className="contact-reveal"><StaggerItem><p className="eyebrow">08 / {locale==="en"?"Contact":"تواصل"}</p><h2>{t.contact}</h2></StaggerItem><StaggerItem><a className="email-link" href={`mailto:${profile.email}`}>{profile.email}<span>↗</span></a></StaggerItem><StaggerItem className="contact-meta"><a href="https://wa.me/967781830031?text=Hello%20Mahmoud%2C%20I%20would%20like%20to%20discuss%20a%20project." target="_blank" rel="noopener noreferrer" className="whatsapp-link"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.8a8.5 8.5 0 0 1-12.6 7.4L3 20.5l1.3-4.7a8.5 8.5 0 1 1 16.2-4Z"/><path d="M8.1 7.8c.2-.4.4-.4.7-.4h.5c.2 0 .4.1.5.4l.8 2c.1.3.1.5-.1.7l-.6.7c-.2.2-.1.4 0 .6.7 1.2 1.7 2.1 3 2.7.2.1.4.1.6-.1l.8-1c.2-.2.4-.3.7-.2l1.9.9c.3.1.4.3.4.5 0 .5-.2 1.5-1 2.1-.7.6-1.7.9-2.7.6-1.5-.4-3.4-1.2-5-2.7-1.3-1.2-2.3-2.8-2.7-4.2-.4-1.4 0-2.4.5-3 .5-.5 1.1-.7 1.7-.7Z"/></svg>{locale==="en"?"WhatsApp":"واتساب"} ↗</a><a href={`/resume/Mahmoud-Abdulghani-Almaqrami-CV-${locale==="en"?"English":"Arabic"}.pdf`} download>{t.resume} ↓</a><a href={`tel:${profile.phone.replace(/\s/g,"")}`}>{profile.phone}</a><span>{profile.location[locale]}</span></StaggerItem></Stagger></div></section>
  <footer className="footer container"><span>© 2026 {profile.displayName[locale]}</span><span>{t.footer}</span><a href="#top">↑ {locale==="en"?"Top":"الأعلى"}</a></footer>
 </main></>
}
